version: 0.2

env:
  variables:
    MAVEN_HOME: "/usr/share/maven"
    PATH: "$PATH:$MAVEN_HOME/bin"
    WEATHER_API_KEY: "14bbc7727da84b768a690118250603"
    JAVA_HOME: "/usr/lib/jvm/java-11-amazon-corretto"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing JDK 11 and Maven...
      # Install JDK 11
      - yum update -y
      - yum install -y java-11-amazon-corretto-devel
      # Install Maven
      - yum install -y maven
      # Verify installations
      - java -version
      - mvn -version
      # Set environment variables
      - export JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto
      - export PATH=$PATH:$JAVA_HOME/bin
      - echo "JAVA_HOME=$JAVA_HOME" >> ~/.bashrc
      - echo "PATH=$PATH" >> ~/.bashrc
      - source ~/.bashrc

  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - mvn test

  build:
    commands:
      - echo Build phase started on `date`
      - mvn clean package spring-boot:repackage
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Post-build phase started on `date`
      - mv target/weather-service-1.0-SNAPSHOT.jar app.jar
      - chmod +x scripts/*.sh
      - printf '[{"name":"app.jar","sourceUrl":"app.jar"}]' > filemap.json

artifacts:
  files:
    - app.jar
    - appspec.yml
    - scripts/**/*
    - filemap.json
  discard-paths: no

cache:
  paths:
    - '/root/.m2/**/*'