version: 0.2

env:
  variables:
    MAVEN_HOME: "/usr/share/maven"
    PATH: "$PATH:$MAVEN_HOME/bin"
    WEATHER_API_KEY: "14bbc7727da84b768a690118250603"
    JAVA_HOME: "/usr/lib/jvm/java-11-amazon-corretto"

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing dependencies...
      - amazon-linux-extras enable corretto8
      - yum clean metadata
      - yum install -y java-11-amazon-corretto java-11-amazon-corretto-devel maven
      - export JAVA_HOME=/usr/lib/jvm/java-11-amazon-corretto
      - export PATH=$PATH:$JAVA_HOME/bin
      - java -version
      - mvn -version

  pre_build:
    commands:
      - echo Pre-build phase started on `date`
      - mvn test

  build:
    commands:
      - echo Build phase started on `date`
      - mvn package spring-boot:repackage
      - echo Build completed on `date`

  post_build:
    commands:
      - echo Post-build phase started on `date`
      - mv target/weather-service-1.0-SNAPSHOT.jar app.jar
      - chmod +x scripts/*.sh
      - printf '[{"name":"app.jar","sourceUrl":"app.jar"}]' > filemap.json

artifacts:
  files:
    - app.jar
    - appspec.yml
    - scripts/**/*
    - filemap.json
  discard-paths: no

cache:
  paths:
    - '/root/.m2/**/*'